version: "3"

services:

  runtime-setup:
    image: swift-kafka-client:22.04-5.8
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.8"

  build:
    image: swift-kafka-client:22.04-5.8

  test:
    image: swift-kafka-client:22.04-5.8
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete
      # - SANITIZER_ARG=--sanitize=thread # TSan broken still

  update-benchmark-baseline:
    image: swift-kafka-client:22.04-5.8
    environment:
      - SWIFT_VERSION=5.8

  shell:
    image: swift-kafka-client:22.04-5.8
